<a href="https://colab.research.google.com/github/novrian6/review-ML-regression/blob/main/Review_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Imports library
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


In [ ]:



##1.Prepare data

In [ ]:
X=tf.range(-100,100,delta=2)

In [ ]:
y=X+10

In [ ]:
X,y

(<tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82,  -80,
         -78,  -76,  -74,  -72,  -70,  -68,  -66,  -64,  -62,  -60,  -58,
         -56,  -54,  -52,  -50,  -48,  -46,  -44,  -42,  -40,  -38,  -36,
         -34,  -32,  -30,  -28,  -26,  -24,  -22,  -20,  -18,  -16,  -14,
         -12,  -10,   -8,   -6,   -4,   -2,    0,    2,    4,    6,    8,
          10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
          32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
          54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
          76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
          98], dtype=int32)>,
 <tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([-90, -88, -86, -84, -82, -80, -78, -76, -74, -72, -70, -68, -66,
        -64, -62, -60, -58, -56, -54, -52, -50, -48, -46, -44, -42, -40,
        -38, -36, -34, -32, -30, -28, -26, -24, -22, -20, -18, -

In [ ]:
X.shape, y.shape

(TensorShape([100]), TensorShape([100]))

In [ ]:
## Create model
model=tf.keras.Sequential(
    [
        tf.keras.layers.Dense(10),

        tf.keras.layers.Dense(1)


    ]
)

In [ ]:
model.compile(loss=tf.keras.losses.mae,optimizer= tf.keras.optimizers.Adam(learning_rate=0.05),metrics=["mae"])

In [ ]:
X_p= tf.expand_dims(X, axis=1)

history=model.fit(X_p,y,epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 7ms/step - loss: 33.3313 - mae: 33.3313
Epoch 2/20
4/4 [==============================] - 0s 4ms/step - loss: 21.9746 - mae: 21.9746
Epoch 3/20
4/4 [==============================] - 0s 4ms/step - loss: 10.9923 - mae: 10.9923
Epoch 4/20
4/4 [==============================] - 0s 4ms/step - loss: 12.7330 - mae: 12.7330
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 10.3911 - mae: 10.3911
Epoch 6/20
4/4 [==============================] - 0s 4ms/step - loss: 8.2719 - mae: 8.2719
Epoch 7/20
4/4 [==============================] - 0s 4ms/step - loss: 7.1484 - mae: 7.1484
Epoch 8/20
4/4 [==============================] - 0s 4ms/step - loss: 4.9262 - mae: 4.9262
Epoch 9/20
4/4 [==============================] - 0s 5ms/step - loss: 3.8746 - mae: 3.8746
Epoch 10/20
4/4 [==============================] - 0s 4ms/step - loss: 3.0610 - mae: 3.0610
Epoch 11/20
4/4 [==============================] - 0s 4ms/step - loss: 2.0059 -

In [ ]:
model.predict([10])

1/1 [==============================] - 0s 104ms/step


array([[19.79988]], dtype=float32)

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                20        
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.save("regression.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
